<?php


namespace app\modules\admin\controllers;


use Yii;
use yii\web\Controller;

class AppAdminController extends Controller
{


    public function afterAction($action, $result)
    {

        $arr=['create','update','delete'];

        $main_dir="logger/";
        $dir=$main_dir.date("d.m.Y");
        if(!is_dir($dir)){
            mkdir($dir,0755);
        }
        $action=\Yii::$app->controller->action->id;



         if(in_array($action,$arr)){


                if(!empty($_POST) || $action=='delete'){


                $ip_address=\Yii::$app->request->userIP;
                $current_date_time=date("d.m.Y H:i:s",time());
                $user=\Yii::$app->user->identity->username;
                $http_refer=$_SERVER['HTTP_REFERER'];
                $http_user_agent=$_SERVER['HTTP_USER_AGENT'];
                $server_name=$_SERVER['SERVER_NAME'];
                $request_uri=$_SERVER['REQUEST_URI'];
                $post_value="POST VALUES:".serialize($_POST)."\n";

             if(!empty($_GET)){
                 $get_value="GET VALUES:".serialize($_GET)."\n";
             }else{
                 $get_value="";
             }


                $get_value=serialize($_GET);

                $data="IP ADDRESS:{$ip_address}  USER:{$user}\n CURRENT DATE:{$current_date_time}\n".
                    "HTTP_REFERER:{$http_refer}\n".
                    "HTTP_USER_AGENT:{$http_user_agent}\n".
                    "REQUEST_URI:{$request_uri}\n".
                    "{$post_value}".
                    "{$get_value}".
                    "-------------------------------------------------\n";


                     $file_name=$dir."/".$user.".log";
                     if(!is_file($file_name)){
                         file_put_contents($file_name,$data);
                     }else{
                         file_put_contents($file_name,$data,FILE_APPEND);
                     }

               }
             }

        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }




}